### PR TITLE
Refact default fork block

### PR DESCRIPTION
**Pull request by PabloLefort**
Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
Yeah, what you've done here is not behaviorally the same as the previous code (due to the case that @carver posted)

**Comment by PabloLefort** [comment]
Yup, we saw the same. But, just trying..
```python
>>> def a(i):
...     print(i or 0)
... 
>>> a(0)
0
>>> a(1)
1
>>> a(None)
0
```

**Comment by carver** [comment]
But this PR works more like:

```py
def printer(my_num=0):
    print(my_num)

>>> printer(0)
0
>>> printer(1)
1
>>> printer(None)
None
>>> printer(my_num=None)
None
```

**Comment by PabloLefort** [comment]
Yes. I'll revert this.
Thanks either!

**Pull request closed without merging**
