### PR TITLE
Catch py-evm BlockNotFound, reraise as eth-tester BlockNotFound

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

eth-tester was raising a py-evm exception that web3 didn't recognize: `BlockNotFound`

### How was it fixed?

catch and re-raise the exception as an eth-tester standard `BlockNotFound`

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by carver** [comment]
Py2 compatibility issues.

Will rebase on #45

**Comment by pipermerriam** [comment]
You can rebase on master now.

**Comment by carver** [comment]
Ah, equivalent problem in the other backends, I'll fix those too.

**Comment by carver** [comment]
I think the CI lag actually got worse after moving to the ethereum org queue :(

**Comment by carver** [comment]
Took 4 hours to kick off, 6 min to run :/

**Comment by carver** [comment]
And now that I look at it, I want to change it again, haha.

Basically, something like:

```py
@standardize_exceptions({EVMBlockNotFound: BlockNotFound})
```

So I can avoid the instance attribute.

I might have to do something a little squirrelly like define EVMBlockNotFound = None if pyevm isn't available.

**Comment by pipermerriam** [comment]
ping @jpitts 

Can you double check our travis subscription is active.  Sounds like we might be running at capacity and could maybe benefit from bumping our number of dedicated workers up a bit more.

**Comment by pipermerriam** [comment]
Yes, that API seems better.  Will wait on merge.

**Pull request merged**
