### PR TITLE
Upgrade to py-evm v0.2.0-alpha.43

### PR DESCRIPTION
**Pull request by carver**
### What was wrong?

related to #157 

### How was it fixed?

It's not, just showing what the tasks are for upgrading. For example, stop referencing `account_db` directly, and use vm state, like: `vm.state.get_balance(acct)` instead of `vm.state.account_db.get_balance(acct)`

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by fubuloubu** [comment]
I screwed #161 up and based it off `pyevm-upgrade` instead of `master`. So it never got merged.

**Comment by carver** [comment]
whoops, and I deleted the branch X)

**Comment by carver** [comment]
Do you have it handy to re-push?

**Comment by fubuloubu** [comment]
Me too 😛

**Comment by fubuloubu** [comment]
Still available! https://github.com/ethereum/eth-tester/tree/pyevm-upgrade?files=1

**Comment by carver** [comment]
Oh good! Done...

**Pull request closed without merging**
