### PR TITLE
Piper/pyethereum20

### PR DESCRIPTION
**Pull request by pipermerriam**
Replaces #26 

### What was wrong?

Need a backend for the `2.x` pyethereum codebase.

### How was it fixed?

Adding a backend class.  WIP

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
Thanks so much @fubuloubu for getting this off the ground.

**Comment by fubuloubu** [comment]
NP
If you release it on PyPI I'll play around with it tomorrow and look into integration with Viper

**Comment by pipermerriam** [comment]
Available as `0.1.0-beta.6`

**Comment by fubuloubu** [comment]
I tried `$ pip install eth-tester[pyethereum20]==0.1.0-beta.6` but it couldn't find the pyethereum extra. Did I do something wrong?

**Comment by pipermerriam** [comment]
@fubuloubu I found that `ethereum>=2.0.0,<2.1.0` had some API deficiencies in the `ethereum.tools.tester` module that were hard to work around so I bumped to require `>=2.1.0`.

**Pull request merged**
