### PR TITLE
fix: update pin of py-evm to stop typing-extensions pinning issues

### PR DESCRIPTION
**Pull request by fubuloubu**
### To-Do:

- [ ] Add entry to the [release notes](https://github.com/ethereum/eth-tester/blob/master/newsfragments/README.md)

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by fubuloubu** [comment]
Ugh and `eth-account` needs to update pin of `eth-keys`

**Comment by kclowes** [comment]
Yeah, this is high on my list @fubuloubu. We have to do it down the whole chain.

**Comment by fubuloubu** [comment]
> Yeah, this is high on my list @fubuloubu. We have to do it down the whole chain.

Thanks! Sorry about opening these PRs, was hoping that it'd be easier, but at least we can keep track of the conversation a bit more. We have a workaround by forcing `type-extensions` to get docker working but ofc would rather avoid that.

**Comment by kclowes** [comment]
No worries, thanks for taking initiative! I was out for the holidays and am just now catching up, so you should see some progress here shortly. I'm glad to hear you have a workaround in the meantime!

**Comment by kclowes** [comment]
Closing in favor of #230. Thanks again!

**Pull request closed without merging**
