### PR TITLE
Replace left_pad with rjust

### PR DESCRIPTION
**Pull request by dylanjw**
### What was wrong?
left_pad was removed from eth-utils.

### How was it fixed?
replaced left_pad with rjust built-in method.

#### Cute Animal Picture

Cute animal picture

### CODE REVIEW

**Comment by pipermerriam** [comment]
The py-evm ones should be fixed with https://github.com/ethereum/py-evm/pull/380

Still need to fix the pyethereum ones.

**Comment by dylanjw** [comment]
Should `force_bytes` be removed as well?

**Comment by carver** [comment]
> Should force_bytes be removed as well?

Yes

**Comment by carver** [comment]
Looks good so far

**Comment by pipermerriam** [comment]
Also, `eth-utils` in setup.py should be `eth-utils>=1.0.0b2,<2.0.0`.

You can also pin all dependencies within a major version while you're there if they are not already.

**Comment by pipermerriam** [comment]
`eth-keys` should also be bumped to the latest beta release.

**Comment by dylanjw** [comment]
@pipermerriam @carver I think Im getting a little off track.  Maybe you could orient me a bit?

the function `stringify` eth_tester/backends/mock/factory.py uses force_bytes in a couple places:

```
@apply_to_return_value(b'|'.join)
@to_tuple
def stringify(value):
    if is_bytes(value):
        yield value
    elif is_text(value):
        yield force_bytes(value)
    elif is_list_like(value):
        yield b''.join((
            b'(',
            b','.join((stringify(item) for item in value)),
            b')',
        ))
    elif is_dict(value):
        yield b''.join((
            b'{',
            b','.join((
                b":".join((stringify(key), stringify(item)))
                for key, item
                in value.items()
            )),
            b'}',
        ))
    elif is_integer(value):
        yield force_bytes(str(value))
    elif is_null(value):
        yield 'None@{0}'.format(id(value))
    else:
        raise TypeError("Unsupported type for stringification: {0}".format(type(value)))
```

`stringify` is used later in the mock/factory.py to process values being fed into keccack().

Should I be updating `stringify`, or make changes further up the call stack such that no values need processing at this point, so stringify can be removed?

**Comment by carver** [comment]
`stringify` is a confusing name for this. It's more like `bytes_repr`.

I think modifying the implementation there is ok.

```py
    elif is_text(value):
        yield force_bytes(value)
```

to:
```py
    elif is_text(value):
        yield to_bytes(text=value)
```

and:
```py
    elif is_integer(value):
        yield force_bytes(str(value))
```

to:
```py
    elif is_integer(value):
        yield to_bytes(text=str(value))
```

_I don't know why it's converting int to str and then to bytes, but this is how to write such a thing. If all tests succeed with `yield to_bytes(value)` in the last code block, then I would do that instead._

**Pull request merged**
